laboratorio-8/lab8/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from lab8 import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pokedex.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

laboratorio-8/pokedex/urls.py
from django.urls import path

from . import views
app_name= "pokedex"
urlpatterns = [
    path("", views.index, name="index"),
    path("pokemon/<int:pokemon_id>/", views.pokemon, name="pokemon"),
    path("add_pokemon/", views.add_pokemon, name="add_pokemon"),
    path("edit_pokemon/<int:id>/", views.edit_pokemon, name="edit_pokemon"),
    path("login/", views.CustomLoginView.as_view(), name='login'),
    path("delete_pokemon/<int:id>/", views.delete_pokemon, name="delete_pokemon"),
    path("delete_trainer/<int:id>/", views.delete_trainer, name="delete_trainer"),              
    path("edit_trainer/<int:id>/", views.edit_trainer, name="edit_trainer"),                    
    path("add_trainer/", views.add_trainer, name="add_trainer"),                                
]

laboratorio-8/pokedex/models.py
from django.db import models


class Trainer(models.Model):
    first_name = models.CharField(max_length=30, null=False)
    last_name = models.CharField(max_length=30, null=False)
    birth_date = models.DateField(null=False)
    level = models.IntegerField(default=1)

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

class Pokemon(models.Model):
    name = models.CharField(max_length=30, null=False)
    POKEMON_TYPES = {
        ('A', 'Agua'),
        ('F', 'Fuego'),
        ('T', 'Tierra'),
        ('P','Planta'),
        ('E','Eléctrica'),
        ('R','Reptil'),

            }
    type = models.CharField(max_length=30, choices=POKEMON_TYPES, null=False)
    weight = models.DecimalField(null=False, default=1, max_digits=4, decimal_places=2)
    height = models.DecimalField(null=False, default=1, max_digits=4, decimal_places=2)
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='pokemons_images')


    def __str__(self) -> str:
        return self.name

                              

laboratorio-8/pokedex/forms.py
from django import forms
from .models import Trainer, Pokemon


class PokemonForm(forms.ModelForm):
    class Meta:
        model = Pokemon
        fields = '__all__'
        widgets = {

                'name': forms.TextInput(attrs={'class': 'form-control'}),
                'type': forms.Select(attrs={'class': 'form-control'}),
                'weight': forms.TextInput(attrs={'class': 'form-control'}),
                'height': forms.TextInput(attrs={'class': 'form-control'}),
                'trainer': forms.Select(attrs={'class': 'form-control'}),
                'picture': forms.ClearableFileInput(attrs={'class': 'form-control-file'})
                }

class TrainerForm(forms.ModelForm):                                                            
    class Meta:                                                                                 
        model = Pokemon                                                                         
        fields = '__all__'                                                                      
        widgets = {                                                                             
                                                                                                
                'name': forms.TextInput(attrs={'class': 'form-control'}),                       
                'type': forms.Select(attrs={'class': 'form-control'}),                          
                'weight': forms.TextInput(attrs={'class': 'form-control'}),                     
                'height': forms.TextInput(attrs={'class': 'form-control'}),                     
                'trainer': forms.Select(attrs={'class': 'form-control'}),                       
                'picture': forms.ClearableFileInput(attrs={'class': 'form-control-file'})       
                }                                                                               
   

laboratorio-8/pokedex/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template import loader
from .models import Pokemon, Trainer
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from pokedex.forms import PokemonForm, TrainerForm

def index(request):
    pokemons = Pokemon.objects.order_by('type')
    trainers = Trainer.objects.order_by('level')
    template = loader.get_template('index.html')
    return HttpResponse(template.render({'pokemons': pokemons}, request))

def pokemon(request, pokemon_id):
    pokemon = get_object_or_404(Pokemon, pk=pokemon_id)
    template = loader.get_template('display_pokemon.html')
    context = {
        'pokemon': pokemon
    }
    return HttpResponse(template.render(context, request))

def add_pokemon(request):
    if request.method == 'POST':
        form = PokemonForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('pokedex:index')
    else:
        form = PokemonForm()

    return render(request, 'pokemon_form.html', {'form':form})


class CustomLoginView(LoginView):
    template_name="login.html"


@login_required
def edit_pokemon(request, id):
    pokemon = get_object_or_404(Pokemon, pk=id)
    if request.method == 'POST':
        form = PokemonForm(request.POST, request.FILES, instance=pokemon)
        if form.is_valid():
            form.save()
            return redirect('pokedex:index')
    else:
        form = PokemonForm(instance=pokemon)
        

    return render(request, 'pokemon_form.html', {'form':form})


@login_required
def delete_pokemon(request, id):
    pokemon = get_object_or_404(Pokemon, pk=id)
    pokemon.delete()
    return redirect("pokedex:index")

# Trainer Section

def trainer(request, trainer_id):                                                                
    trainer = get_object_or_404(Trainer, pk=pokemon_id)                                          
    template = loader.get_template('display_trainer.html')                                       
    context = {                                                                                  
        'trainer': trainer                                                                       
    }                                                                                            
    return HttpResponse(template.render(context, request))                                       
@login_required                                                                                                 
def add_trainer(request):                                                                        
    if request.method == 'POST':                                                                 
        form = TrainerForm(request.POST, request.FILES)                                          
        if form.is_valid():                                                                      
            form.save()                                                                          
            return redirect('pokedex:index')                                                     
    else:                                                                                        
        form = TrainerForm()                                                                     
                                                                                                 
    return render(request, 'trainer_form.html', {'form':form})                                   
                                                                                                 
                                                                                                 
class CustomLoginView(LoginView):                                                                
    template_name="login.html"                                                                   
                         



@login_required                                                                                  
def edit_trainer(request, id):                                                                   
    pokemon = get_object_or_404(Trainer, pk=id)                                                  
    if request.method == 'POST':                                                                 
        form = TrainerForm(request.POST, request.FILES, instance=pokemon)                        
        if form.is_valid():                                                                      
            form.save()                                                                          
            return redirect('pokedex:index')                                                     
    else:                                                                                        
        form = TrainerForm(instance=trainer)                                                     
                                                                                                 
                                                                                                 
    return render(request, 'trainer_form.html', {'form':form})                                   
                                                                                                 
                                                                                                 
@login_required                                                                                  
def delete_trainer(request, id):                                                                 
    trainer = get_object_or_404(Trainer, pk=id)                                                  
    trainer.delete()                                                                             
    return redirect("pokedex:index")   

laboratorio-8/pokedex/templates/add_pokemon.html
{% extends "base.html" %}
{% block title%}Pokedex{% endblock title %}

{% block content  %}

	<form method="post" enctype="multipart/form-data"></form>
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="btn btn-primary">Guardar<button>
		</form>
                {% endblock content %}

laboratorio-8/pokedex/templates/base.html
<html>
    <head>
	{% load static %}
	<title>{% block title%}{% endblock title %}</title>
	<!--        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">-->
	<link rel="stylesheet"  href="{% static "bootstrap.css" %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="container">



            <div class="bg-primary text-white p-4 text-center">
                <h1>Mi Pokedex</h1>
		<img src="{%static "logo.png"%}" style="max-width: 400px; height: auto;">
            </div>

	    	<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
		<a class="nav-link active" aria-current="page" href="{% url "pokedex:index" %}">Home</a>
        </li>
	{% if user.is_authenticated %}
        <li class="nav-item">
		<a class="nav-link" href="{% url "pokedex:add_pokemon" %}">Añadir Pokemon</a>
        </li>
        <li class="nav-item">                                                                   
                <a class="nav-link" href="{% url "pokedex:add_trainer" %}">Añadir Entrenador</a>   
        </li>  
                <li class="nav-item">
                <a class="nav-link" href={% url "logout" %}>Logout</a>
        </li>

	{% else %}
        <li class="nav-item">
		<a class="nav-link" href={% url "pokedex:login" %}>Login</a>
	</li>
	{% endif %}
      </ul>
      <span class="navbar-text">
        "Gotta Catch'em All!"
      </span>
    </div>
  </div>
</nav>
        	{% block content %} {% endblock content %}
	</div>
    </body>
</html>

laboratorio-8/pokedex/templates/display_pokemon.html
{% extends "base.html" %}
{% block title%}Pokedex{% endblock title %}

{% block content  %}
            
	<p>Has elegido al pokemon: <strong>{{ pokemon | capfirst }}</strong></p>
            <h3>Características del Pokemon:</h3>
	    <ul>
            <li>Tipo: {{pokemon.type}}</li>
            <li>Peso: {{pokemon.weight}} Kg.</li>
            <li>Altura: {{pokemon.height}} Cm.</li>
	    </ul>
		    <a href ="/">Regresar<a>
        </div>
    </body>
</html>

{% endblock content %}

laboratorio-8/pokedex/templates/display_trainer.html
{% extends "base.html" %}
{% block title%}Pokedex{% endblock title %}

{% block content  %}
            
	<p>El entrenador es: <strong>{{ trainer | capfirst }}</strong></p>
            <h3>Datos del Entrenador:</h3>
            <ul>
            <li>Edad: {{pokemon.age}}</li>
            <li>Altura: {{pokemon.height}} Kg.</li>
            <li>Ciudad de Nacimiento: {{pokemon.city}} Cm.</li>
            </ul>
                    <a href ="/">Regresar<a>
        </div>
    </body>
</html>

{% endblock content %}

laboratorio-8/pokedex/templates/index.html
{% extends "base.html" %}
{% block title%}Pokedex{% endblock title %}

{% block content  %}
		   
	<p class="p-2">Django first website.</p>
	<a href="{% url "pokedex:add_pokemon" %}">Crear Pokemon</a>
		<div class = "card-group">
			{% for pokemon in pokemons%}
				<div class='card'>
					<img src="{{ pokemon.picture.url }}" alt = "" style="max-width: 200px; height: auto;">
					<div class = "card-body">
						<h5 class='card-title'>{{ pokemon }}</h5>
						<p class="card-text">Entrenador:{{ pokemon.trainer }}</p>
						<p class= "card-text">Peso:{{ pokemon.weight }}</p>
						<a href = "pokemon/{{pokemon.id}}" class="btn btn-primary">
<i class="fa-solid fa-eye"></i>
						</a>
						<a href = "edit_pokemon/{{pokemon.id}}" class="btn btn-secondary">
		<i class="fa-solid fa-pencil"></i>
                                                </a>
						<a href = "delete_pokemon/{{pokemon.id}}" class="btn btn-danger">
                <i class="fa-solid fa-trash"></i>
                                                </a>


				</div>
		</div>
		{% endfor %}
		</div>
 <div class = "card-group">                                                      
                        {% for trainer in trainers%}                                            
                                <div class='card'>                                              
                                        <img src="{{ trainer.picture.url }}" alt = "" style="max-width: 200px; height: auto;">                                                                  
                                        <div class = "card-body">                               
                                                <h5 class='card-title'>{{ trainer }}</h5>       
                                                <p class="card-text">Edad:{{ pokemon.birth_date }}</p>                                                                                       
                                                <p class= "card-text">Nivel:{{ pokemon.level }}</p>                                                                                             
                                                <a href = "pokemon/{{trainer.id}}" class="btn btn-primary">                                                                                     
<i class="fa-solid fa-eye"></i>                                                                 
                                                </a>                                            
                                                <a href = "edit_trainer/{{trainer.id}}" class="btn btn-secondary">                                                                              
                <i class="fa-solid fa-pencil"></i>                                              
                                                </a>                                            
							<a href = "delete_trainer/{{trainer.id}}" class="btn btn-danger">                                                                                 
                <i class="fa-solid fa-trash"></i>                                               
                                                </a>                                            
                                                                                                
                                                                                                
                                </div>                                                          
                </div>                                                                          
                {% endfor %}                                                                    
                </div>     
		{% endblock content %}

laboratorio-8/pokedex/templates/login.html
{% extends "base.html" %}
{% block title%}Login{% endblock title %}

{% block content  %}

<div class="row d-flex justify-content-center">
	<div class="col-md-6">
		<h2>Inicio de sesión</h2>
		<form action="{% url "pokedex:login" %}" method="post">		
			{% csrf_token %}
			<div>
				<label for="username">Usuario:</label>
				<input type="text" name="username" id="username" required>
			</div>
			<div>
				<label for "password"> Contraseña:</label>
				<input type="password" name="password" id="password" required>
			</div>
			<button type="submit" class="btn btn-primary">Ingresar</button>
		</form>
	</div>	   
</div>
{% endblock content %}

laboratorio-8/pokedex/templates/pokemon_form.html
{% extends "base.html" %}
{% block title%}Pokedex{% endblock title %}

{% block content  %}

	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="btn btn-primary">Guardar<button>
		</form>
                {% endblock content %}

laboratorio-8/pokedex/templates/trainer_form.html
{% extends "base.html" %}
{% block title%}Pokedex{% endblock title %}

{% block content  %}

        <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Guardar<button>
                </form>
                {% endblock content %}